<?php

/**
 * @file
 * The field_bundle_canonial module file.
 */


/**
 * Implements hook_entity_type_build().
 */
function field_bundle_canonical_entity_type_build(array &$entity_types) {
  if (!isset($entity_types['field_bundle'])) {
    return;
  }
  /** @var \Drupal\Core\Entity\EntityTypeInterface $entity_type */
  $entity_type = $entity_types['field_bundle'];
  $entity_type->setLinkTemplate('canonical', '/field-bundle/{field_bundle}');
}
