<?php

/**
 * @file
 * Enables Group functionality for the Field bundles.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function group_field_bundle_field_bundle_config_insert() {
  \Drupal::service('plugin.manager.group_content_enabler')->clearCachedDefinitions();
}

/**
 * Implements hook_entity_operation().
 */
function group_field_bundle_entity_operation(EntityInterface $entity) {
  $operations = [];

  if ($entity->getEntityTypeId() == 'group' && \Drupal::moduleHandler()->moduleExists('views')) {
    /** @var \Drupal\group\Entity\GroupInterface $entity */
    if ($entity->hasPermission('access group_field_bundle overview', \Drupal::currentUser())) {
      /** @var \Symfony\Component\Routing\RouterInterface $router */
      $router = \Drupal::service('router.no_access_checks');
      if ($router->getRouteCollection()->get('view.group_field_bundle.page_1') !== NULL) {
        $operations['field_bundles'] = [
          'title' => t('Field bundles'),
          'weight' => 40,
          'url' => Url::fromRoute('view.group_field_bundle.page_1', ['group' => $entity->id()]),
        ];
      }
    }
  }

  return $operations;
}
