<?php

/**
 * @file
 * Install, uninstall and update hooks for the Field Bundle module.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 */
function field_bundle_install() {
  // Grant the "view field_bundle" permission to all users by default.
  user_role_grant_permissions(RoleInterface::ANONYMOUS_ID, ['view field_bundle']);
  user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, ['view field_bundle']);
}
